import { resolve } from "$app/paths";
import { csvFormat, csvFormatRows, csvFormatBody } from "d3-dsv";
import { get, set, update } from "./db.js";
import { decompressData } from "compress-csv-to-json";
import { initialState, geotypesLookup } from "./config.js";
import { getName, makeFilename } from "./geo.svelte.js";
import { makeDateFormatter } from "./data-utils.js";

async function loadCompressedData(key, path, fn) {
	const val = await get(key);
	if (val) return val;

	const rawData = await (await fetch(resolve(path))).json();
	const data = decompressData(rawData, fn);
	await set(key, data);
	return data;
}

export async function getAreasList() {
	const fn = (d, i) => ({
		areacd: d[0][i],
		areanm: d[1][i],
		parentcd: d[2][i]
	});
	const data = await loadCompressedData("areasList", "/data/places-list.json", fn);
	const lookup = Object.fromEntries(data.map((d) => [d.areacd, d]));
	for (const d of data) {
		const type = geotypesLookup[d.areacd.slice(0, 3)] || null;
		const parent = lookup[d.parentcd]?.areanm;
		d.group = parent ? `${type} in ${parent}` : type;
	}
	return data;
}

export async function getBestFits() {
	const key = "bestFits";
	const val = await get(key);
	if (val) return val;

	const path = "/data/bestfit-lookup.json";
	const data = await (await fetch(resolve(path))).json();
	await set(key, data);
	return data;
}

export async function getOAdata() {
	const fn = (d, i) => ({
		oa21cd: d[0][i],
		lsoa21cd: d[1][i],
		msoa21cd: d[2][i],
		ltla21cd: d[3][i],
		rgn21cd: d[4][i],
		lng: d[5][i],
		lat: d[6][i],
		population: d[7][i]
	});
	return await loadCompressedData("oaData", "/data/oa21-data.json", fn);
}

export async function getLSOAcentroids() {
	const fn = (d, i) => ({
		lsoa21cd: d[0][i],
		lng: d[1][i],
		lat: d[2][i]
	});
	return await loadCompressedData("lsoaCentroids", "/data/lsoa21-centroids.json", fn);
}

export function sleep(ms = 0) {
	return new Promise((resolve) => setInterval(() => resolve(), ms));
}

export function slugify(str) {
	return str.toLowerCase().replaceAll(" ", "-");
}

export function round(num, precision = 0) {
	const multiplier = Math.pow(10, precision);
	return Math.round(num * multiplier) / multiplier;
}

// Recursive function to round numbers in a multi-array (used to round coordinates)
export function roundAll(arr, decimals) {
	let newarr = [];
	arr.forEach((d) => {
		if (typeof d == "number") {
			newarr.push(round(d, decimals));
		} else if (Array.isArray(d)) {
			newarr.push(roundAll(d, decimals));
		} else {
			newarr.push(d);
		}
	});
	return newarr;
}

export function groupData(data, key) {
	let dataIndexed = {};
	for (const d of data) {
		if (!dataIndexed[d[key]]) {
			dataIndexed[d[key]] = {
				label: d[key],
				values: []
			};
		}
		dataIndexed[d[key]].values.push(d);
	}
	return Object.values(dataIndexed);
}

export function download(blob, filename) {
	let url = window.URL || window.webkitURL || window;
	let link = url.createObjectURL(blob);
	let a = document.createElement("a");

	a.download = filename;
	a.href = link;
	document.body.appendChild(a);

	a.click();
	document.body.removeChild(a);
}

export async function clip(str) {
	return await navigator.clipboard.writeText(str);
}

function formatTable(table, name, compName) {
	const nameLookup = { MyCustomArea: name, ComparisonArea: compName };
	const dateFormat = makeDateFormatter(table.meta.dateFormat);
	const rows = {};

	for (const d of table.data) {
		const rowId = `${d.date}_${d.category}`;
		if (!rows[rowId])
			rows[rowId] = {
				Variable: table.meta.label,
				Category: d.category,
				[`${name} (count)`]: null,
				...(compName ? { [`${compName} (count)`]: null } : {}),
				[`${name} (%)`]: null,
				...(compName ? { [`${compName} (%)`]: null } : {}),
				Unit:
					table.meta.unit === "%" ? table.meta.base.replace("all ", "") : table.meta.unit,
				"Base population": table.meta.base,
				Source: table.meta.source,
				Geography: table.meta.geography === "lsoa21" ? "LSOA" : "Output Area",
				"Time period": dateFormat(d.date)
			};
		const col = `${nameLookup[d.areanm]} (${d.measure === "Value" ? "count" : "%"})`;
		rows[rowId][col] = d.value;
	}

	return Object.values(rows);
}

export function downloadData(tables, activeArea, comparisonArea) {
	const name = getName(activeArea);
	const compName = comparisonArea ? getName(comparisonArea) : null;

	const localeOptions = { year: "numeric", month: "short", day: "numeric" };
	const header = [
		`Custom area profile data for ${name}`,
		"Source: Office for National Statistics",
		"",
		`Data generated by the ONS Build a Custom Area Profile tool on ${new Date().toLocaleDateString(
			"en-GB",
			localeOptions
		)}`,
		"The data in this profile are aggregated from small areas on a best-fit basis, and therefore may differ slightly from other sources."
	];

	const data = tables.map((tab) => formatTable(tab, name, compName)).flat();
	const csv = csvFormatRows(header.map((d) => [d])) + "\n\n" + csvFormat(data);
	const blob = new Blob([csv], { type: "text/csv" });
	download(blob, makeFilename(activeArea, "csv"));
}

export function downloadDataset(table, data, columns) {
	const localeOptions = { year: "numeric", month: "short", day: "numeric" };
	const header = [
		`${table.label}`,
		`${table.summary}`,
		`Source: ${table.source}`,
		"",
		`Data generated by the ONS Build a Custom Area Profile tool on ${new Date().toLocaleDateString(
			"en-GB",
			localeOptions
		)}`,
		"The data in this profile are aggregated from small areas on a best-fit basis, and therefore may differ slightly from other sources."
	];

	const csv =
		csvFormatRows(header.map((d) => [d])) +
		"\n\n" +
		columns.join(",") +
		"\n" +
		csvFormatBody(data);
	const blob = new Blob([csv], { type: "text/csv" });
	download(blob, slugify(table.label));
}
