import { mapObject, centroids, selected, state, version } from "$lib/stores/mapstore";
import { get } from "svelte/store";
import { buildstate, tables } from "$lib/stores/mapstore";
import { analyticsEvent } from "$lib/layout/AnalyticsBanner.svelte";
import { download, clip } from "$lib/util/functions";
import { cdnbase } from "$lib/config/geography";
import topicsAll from "$lib/config/topics.json";
import getTable from "$lib/util/get-table";


const topicsLookup = Object.fromEntries(topicsAll.map((d) => [d.code, d]));


export function filterTopics(allTopics, level, coverage) {
  return allTopics
    .filter(t=>t.inVersion.includes(get(version)))//just topics in version 2
    .filter(geographyFilter(level))
    .filter(
      (t) => !t.coverage || coverage.every((c) => t.coverage.includes(c))
    );
}

export function updateLocalStorage(name) {
  let ls = JSON.parse(localStorage.getItem("onsbuild"));
  ls.properties.name = name;
  localStorage.setItem("onsbuild", JSON.stringify(ls));
}

let cache = {};// this is the same if the area changes, so need to make a unique cache for each area somehow




export async function getData(data, comp) {
  let compressedCodes = get(buildstate).compressed.join("") || "default";
  cache[compressedCodes] ||= {}; // Only create a new object if it doesn't exist
  let cacheForArea = cache[compressedCodes];
  if (!get(buildstate).start) return [];

  cacheForArea[comp] ||= {};
  let tables = await Promise.all(
    data.map(async (d) => {
      if (!cacheForArea[comp][d.code]) {
        cacheForArea[comp][d.code] = await getTable(d, get(buildstate), comp);
      }
      return { code: d.code, data: cacheForArea[comp][d.code] };
    })
  );

  return tables;
}

export function groupTopics(topics) {
  return topics.reduce((acc, item) => {
    if (!acc[item.topic]) acc[item.topic] = [];
    acc[item.topic].push(item);
    return acc;
  }, {});
}

export async function checkForHashSelection() {
  let hash = window.location.hash;
  if (hash.match(/#[EKNSW]\d{8}/)) {
    let code = hash.slice(1);
    try {
      const info = await getAreaData(code);
      localStorage.setItem("onsbuild", JSON.stringify(info));
      analyticsEvent({ event: "hashSelect", areaCode: code, areaName: info.properties.name });
    } catch (err) {
      console.error("Error fetching or processing data:", err);
      history.replaceState(null, "", " ");
    }
  }
}

export async function getAreaData(code, options = {}) {
  const res = await fetch(`${cdnbase}/${code.slice(0, 3)}/${code}.json`);
  const data = await res.json();
  const compressed = data.properties.c21cds;

  return {
    geojson: data,
    properties: {
      oa_all: !options?.comparison ? get(centroids).expand(compressed, 'oa') : null,
      compressed,
      name: data.properties.hclnm
        ? data.properties.hclnm
        : data.properties.areanm
          ? data.properties.areanm
          : code,
      highestLevel: get(centroids).identifyHighestGeography(compressed),
    },
  };
}

export function getName() {
  let name = buildstate.name ? buildstate.name : "selected area";
  return name[0].toUpperCase() + name.slice(1)
}

export async function downloadData() {
  let csv = `"Custom area profile data for ${getName()}"\n`;
  csv += `"Source: Office for National Statistics - Census 2021"\n\n`;
  csv += `"Data generated by the Build a custom area profile tool on ${new Date().toLocaleDateString(
    "en-GB",
    { year: "numeric", month: "short", day: "numeric" }
  )}"\n`;
  csv += `"The data in this profile are aggregated from small areas on a best-fit basis, and therefore may differ slightly from other sources."\n\n`;
  csv += `"Variable","Category","${getName("capitalise")}","${get(buildstate).comparison.areanm}","Unit","${getName("capitalise")}","${get(buildstate).comparison.areanm}","Unit","Base population","Source","Geography","Time period"\n`;

  get(tables).forEach((t) => {
    let meta = topicsLookup[t.code];
    let len = meta.categories.length;
    for (let i = 0; i < len; i++) {
      csv += `"${meta.label
      }","${meta.categories[i].label
      }",${t.code == 'population_mye' ? "NA" : t.data[i].percentage ? t.data[i].value : "NA"
      },${t.code == 'population_mye' ? "NA" : t.data[len + i].percentage ? t.data[len + i].value : "NA"
      },"%","${t.data[i].percentage ? t.data[i].count : t.data[i].value
      }","${t.data[len + i].percentage ? t.data[len + i].count : t.data[len + i].value
      }","${meta.base.replace(
        "all ",
        ""
      )}","${meta.base}","${meta.source}","${geographyLookup[meta.lowestGeography]}","${meta.dateLabelLong ? meta.dateLabelLong : "2021"}"\n`;
    }
  });

  var file = new Blob([csv], { type: "text/csv" });
  download(
    file,
    `${buildstate.name ? buildstate.name.replaceAll(" ", "_") : "custom_area_data"}.csv`
  );
  let opts = buildstate.name ? { areaName: buildstate.name } : {};
  analyticsEvent({ event: "fileDownload", fileExtension: "csv", ...opts });
}

// Define geography levels from lowest to highest
export const GEOGRAPHY_LEVELS = ["oa", "lsoa", "msoa", "ltla"];

export const geographyLookup = {
  oa: "Output area",
  lsoa: "Lower layer super output area",
  msoa: "Middle layer super output area",
  ltla: "Lower tier local authority",
};

export function makeEmbed(embedHash) {
  let url = `https://www.ons.gov.uk/visualisations/customprofiles/embed/${embedHash}`;
  return `<div id="custom-profile"></div>
    <script src="https://cdn.ons.gov.uk/vendor/pym/1.3.2/pym.min.js"><\/script>
    <script>var pymParent = new pym.Parent("custom-profile", "${url}", {name: "custom-profile", title: "Embedded area profile"});<\/script>`;
}

export function savePNG(pymParent){
  pymParent.sendMessage("makePNG", null);
  let opts = get(buildstate).name ? { areaName: get(buildstate).name } : {};
  analyticsEvent({
    event: "fileDownload",
    fileExtension: "png",
    ...opts,
  });
}

export function copyEmbed(embedHash) {
  clip(makeEmbed(embedHash), "Copied embed code to clipboard");
  let opts = get(buildstate).name ? { areaName: get(buildstate).name } : {};
  analyticsEvent({ event: "embed", ...opts });
}

export function showEmbed() {
  buildstate.update((s) => ({ ...s, showEmbed: !s.showEmbed }));

  setTimeout(() => {
    const el = document.querySelector("textarea");
    if (!el) return;

    el.scrollIntoView({
      behavior: "smooth",
    });
  });
}

// Creates a lowest available geography filter function for use in a filter chain
export function geographyFilter(selectedGeography) {
  const selectedLevel = GEOGRAPHY_LEVELS.indexOf(
    selectedGeography.toLowerCase()
  );

  // Return a filter function
  return (topic) => {
    // If selected level is lsoa or higher, keep all topics. this is hardcoded
    if (selectedLevel >= GEOGRAPHY_LEVELS.indexOf("lsoa")) {
      return true;
    }
    // For oa, only keep topics with lowestGeography === 'oa'
    return topic.lowestGeography?.toLowerCase() === "oa";
  };
};

export function handleDatasetsShowAllClick() {
  buildstate.update((currentValue) => ({
    ...currentValue,
    showAllDatasets: !currentValue.showAllDatasets
  }))
}

// this the archive version of the function to process uploading a .geojson as a comparison area for the build page.
// It doesn't work
function loadGeo() {
  let file = uploader.files[0] ? uploader.files[0] : null;

  if (file) {
    const reader = new FileReader();

    reader.onload = (e) => {
      try {
        // Read + simplify the boundary
        let b = JSON.parse(e.target.result);

        if (b.type == "FeatureCollection") {
          b = b.features[0];
        } else if (b.type == "Geometry") {
          b = { type: "Feature", geometry: b };
        }
        if (!b.properties) b.properties = {};

        if (!b?.properties?.codes_compressed && b?.geometry) {
          if (JSON.stringify(b.geometry).length > 10000)
            b.geometry = simplifyGeo(b.geometry, 10000);
          const oas = $centroids.contains(b);
          b.properties.codes_compressed = $centroids.compress([...oas.oa]);
        }

        if (b) {
          const props = b.properties;
          state.comparison = {
            areanm: props.areanm
              ? props.areanm
              : props.name
                ? props.name
                : "Custom area",
            areacd: props.areacd
              ? props.areacd
              : props.code
                ? props.code
                : "",
            group: "Uploaded area",
            geometry: b.geometry,
            codes: b.properties.codes_compressed,
          };
          analyticsEvent({
            event: "geoUpload",
            areaName: state.comparison.areanm,
          });
        } else {
          alert("Please upload a valid GeoJSON file.");
        }
      } catch {
        alert("Error. Please make sure you uploaded a valid GeoJSON file.");
      }
    };
    reader.readAsText(file);
  }
}