import { mapObject, centroids, selected, state, user_geometry } from "$lib/stores/mapstore";
import { get } from "svelte/store";
import { buildstate, tables, topicsLookup } from "$lib/stores/mapstore";
import { analyticsEvent } from "$lib/layout/AnalyticsBanner.svelte";
import { download, clip } from "$lib/util/functions";
import { cdnbase } from "$lib/config/geography";



export async function getAreaData(code, options = {}) {
      const res = await fetch(`${cdnbase}/${code.slice(0, 3)}/${code}.json`);
      const data = await res.json();
      const compressed = data.properties.c21cds;
    
    return {
      geojson: data,
      properties: {
        oa_all: !options?.comparison ? get(centroids).expand(compressed,'oa') : null,
        compressed,
        name: data.properties.hclnm
          ? data.properties.hclnm
          : data.properties.areanm
            ? data.properties.areanm
            : code,
        highestLevel: get(centroids).identifyHighestGeography(compressed),
      },
    };
  }

export function getName() {
    let name = buildstate.name ? buildstate.name : "selected area";
    return name[0].toUpperCase() + name.slice(1)
}

export async function downloadData() {
    let csv = `"Custom area profile data for ${getName()}"\n`;
    csv += `"Source: Office for National Statistics - Census 2021"\n\n`;
    csv += `"Data generated by the Build a custom area profile tool on ${new Date().toLocaleDateString(
      "en-GB",
      { year: "numeric", month: "short", day: "numeric" }
    )}"\n`;
    csv += `"The data in this profile are aggregated from small areas on a best-fit basis, and therefore may differ slightly from other sources."\n\n`;
    csv += `"Variable","Category","${getName("capitalise")}","${buildstate.comparison.areanm}","Unit","${getName("capitalise")}","${buildstate.comparison.areanm}","Unit","Base population","Source","Geography","Time period"\n`;

    get(tables).forEach((t) => {
      let meta = get(topicsLookup)[t.code];
      let len = meta.categories.length;
      for (let i = 0; i < len; i++) {
        csv += `"${meta.label}","${meta.categories[i].label}",${
          t.data[i].value ? t.data[i].value : "NA"
        },${t.data[len + i].value ? t.data[len + i].value : "NA"},"${
          meta.unit
        }","${t.data[i].percentage ? t.data[i].count : "NA"}","${
          t.data[len + i].percentage ? t.data[len + i].count : "NA"
        }","${meta.base.replace(
          "all ",
          ""
        )}","${meta.base}","${meta.source}","${geographyLookup[meta.lowestGeography]}","${meta.timePeriod ? meta.timePeriod : "2021"}"\n`;
      }
    });

    var file = new Blob([csv], { type: "text/csv" });
    download(
      file,
      `${buildstate.name ? buildstate.name.replaceAll(" ", "_") : "custom_area_data"}.csv`
    );
    let opts = buildstate.name ? { areaName: buildstate.name } : {};
    analyticsEvent({ event: "fileDownload", fileExtension: "csv", ...opts });
  }

    // Define geography levels from lowest to highest
    export const GEOGRAPHY_LEVELS = ["oa", "lsoa", "msoa", "ltla"];

    export const geographyLookup = {
      oa: "Output area",
      lsoa: "Lower layer super output area",
      msoa: "Middle layer super output area",
      ltla: "Lower tier local authority",
    };

    export function makeEmbed(embedHash) {
        let url = `https://www.ons.gov.uk/visualisations/customprofiles/embed/${embedHash}`;
        return `<div id="custom-profile"></div>
    <script src="https://cdn.ons.gov.uk/vendor/pym/1.3.2/pym.min.js"><\/script>
    <script>var pymParent = new pym.Parent("custom-profile", "${url}", {name: "custom-profile", title: "Embedded area profile"});<\/script>`;
      }

    export function copyEmbed(){ 
        clip(makeEmbed(embedHash), "Copied embed code to clipboard");
        let opts = state.name ? { areaName: state.name } : {};
        analyticsEvent({ event: "embed", ...opts });    
    }

    export function showEmbed(){
        state.showEmbed = !state.showEmbed;

          setTimeout(() => {
            const el = document.querySelector("textarea");
            if (!el) return;

            el.scrollIntoView({
              behavior: "smooth",
            });
    });
    }

    // Creates a lowest available geography filter function for use in a filter chain
    export function geographyFilter(selectedGeography){
      const selectedLevel = GEOGRAPHY_LEVELS.indexOf(
        selectedGeography.toLowerCase()
      );
  
      // Return a filter function
      return (topic) => {
        // If selected level is lsoa or higher, keep all topics. this is hardcoded
        if (selectedLevel >= GEOGRAPHY_LEVELS.indexOf("lsoa")) {
          return true;
        }
        // For oa, only keep topics with lowestGeography === 'oa'
        return topic.lowestGeography?.toLowerCase() === "oa";
      };
    };